
package Frames;

import Frames.Panels.Student_AddPanel;
import Frames.Panels.Student_ListPanel;
import Frames.Panels.Student_UpdatePanel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;


public class Admin_StudentsFrame extends javax.swing.JInternalFrame {

    
    GridBagLayout layout = new GridBagLayout();

    Student_AddPanel p1;
    Student_ListPanel p2;
    Student_UpdatePanel p3;

    public Admin_StudentsFrame() {
        initComponents();
        p1 = new Student_AddPanel();
        p2 = new Student_ListPanel();
        p3 = new Student_UpdatePanel();

        DynamicPanal.setLayout(layout);

        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        
        DynamicPanal.add(p1, c);
        DynamicPanal.add(p2, c);
        DynamicPanal.add(p3, c);

        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddStudent = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        DynamicPanal = new javax.swing.JPanel();

        setBorder(null);
        setClosable(true);
        setTitle("Students  Management");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btnAddStudent.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddStudent.setForeground(new java.awt.Color(204, 204, 204));
        btnAddStudent.setIcon(new javax.swing.ImageIcon("D:\\FCAI\\Year (2)\\Semester (1)\\Computer Programming-2\\Project_1\\New folder\\2000.png")); // NOI18N
        btnAddStudent.setText("Attendance");
        btnAddStudent.setBorderPainted(false);
        btnAddStudent.setContentAreaFilled(false);
        btnAddStudent.setDefaultCapable(false);
        btnAddStudent.setFocusPainted(false);
        btnAddStudent.setFocusable(false);
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnList.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnList.setForeground(new java.awt.Color(204, 204, 204));
        btnList.setIcon(new javax.swing.ImageIcon("D:\\FCAI\\Year (2)\\Semester (1)\\Computer Programming-2\\Project_1\\New folder\\44.png")); // NOI18N
        btnList.setText("List ");
        btnList.setBorderPainted(false);
        btnList.setContentAreaFilled(false);
        btnList.setDefaultCapable(false);
        btnList.setFocusPainted(false);
        btnList.setFocusable(false);
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(btnList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnAddStudent)
                .addGap(62, 62, 62)
                .addComponent(btnList)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        DynamicPanal.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout DynamicPanalLayout = new javax.swing.GroupLayout(DynamicPanal);
        DynamicPanal.setLayout(DynamicPanalLayout);
        DynamicPanalLayout.setHorizontalGroup(
            DynamicPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );
        DynamicPanalLayout.setVerticalGroup(
            DynamicPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:
        p2.setVisible(true);
        p1.setVisible(false);
        p3.setVisible(false);
    }//GEN-LAST:event_btnListActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanal;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnList;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
